### ISSUE TITLE
Homeassistnat CORE installation?

### ISSUE THREAD

**Issue by shahglobal** [guido-syseng/Hassio-Addons#1]
Its a great addon for local audio, It just works very reliably and ques any notifications, I love it. Is there any how to integrating this in "homeassitant core" installation? Any pointer would be awesome to have it working in my pi that have core version of homeassistant, I use core version of HA for a separate pi for rock solid system by enabling overlay file system, and I found that regular homeassistant docker based 
 do not work with overlay file system.
Cheers and thank you so much

**Comment by guido-syseng** [comment]
I'm sorry, but the Addon Notifier was only made for Hassio.
